#!/bin/sh

MODULES="soc_modules"

load_unload() {
	echo ' OK'
}

start() {
	printf 'Starting %s:' "$MODULES"
	chmod 755 /soc/scripts/auto_load_all_drv.sh
	/soc/scripts/auto_load_all_drv.sh
	echo ' OK'
}

stop() {
	printf 'Stopping %s: ' "$MODULES"

	echo 'OK'
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit $?
